site_name: OllamaPrompter
site_author: Yang Wang
repo_url: https://github.com/penguinwang96825/OllamaPrompter
nav:
    - Home: index.md
    - API: api.md
theme:
  name: material
  logo: imgs/logo.png
  favicon: imgs/Favicon.png
  features:
    # - navigation.tabs
    # - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue grey
      accent: indigo 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue grey
      accent: teal

plugins:
  - social
  - mkdocstrings:
      handlers:
        python:
          options:
            parameter_headings: false
            show_object_full_path: false

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/penguinwang96825/OllamaPrompter
    - icon: fontawesome/brands/twitter
      link: https://x.com/yangsheffield
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/yang-wang-sheffield/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg